apiVersion: v1
kind: Secret
metadata:
    name: teslamate-secrets
    namespace: teslamate
    labels:
        app: teslamate
        managed-by: flux
stringData:
    DATABASE_PASS: ENC[AES256_GCM,data:jFhpq88HSPfsbjSMp5RB2S61xokLGnPjhUw9W4JWxnpqqkWoezgn6BpKAe8=,iv:taXsaO+XWdPjD2/MOBeU1ETKHVaqc8luwNQysGUHlFE=,tag:GSptf5G1o7REjppi+VwcDA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:k8Nf3TwwOhioMKQMdU8l3UWh1vVJ0NX+vFC0mq6u1rax9k/GuvAGsl9b/5U=,iv:URPjMrwEmzCSx3eQWTuNoxEHoIu3fQkCO7cpBC5qSvo=,tag:HlGRk6F6zPVV5sNyUhe4xA==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:SwBCyZRmm8gYOkow2dlOqdSfNWFY,iv:nDzLKwxFKpXfbBbKOix7PgF5izAHIQbgMP+Ef5h+Xa8=,tag:J5ALNOLPMFzZC/0gZuLdbQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Usyo5gjpjICBK40oEaB3OYwAeX70sT1SZb8wf76xISZyktYVrL6bR0seOsg=,iv:JHPWBDTotWadszlc5Y7zxEn6Fm5d1QgELcsmmd0fZsY=,tag:l6+7KbVj/7qNWnTT0ExVvw==,type:str]
    #ENC[AES256_GCM,data:kGN5lBszKqVB8EjKskcOPee5srzy,iv:pXtaK/bBRb6XX/E/uABybziig3ouij1Z9iPjK0e5TN0=,tag:YPRRMakNW9OUCCxpuo76Rw==,type:comment]
    GRAFANA_ROOT_URL: ENC[AES256_GCM,data:eLIi8YnOCTxcuTrWWiuxs+9WJLVmtPtONsw=,iv:Ce4CR5KDkigP68V0oPKnsMWjsPShrsc/JAXh6eCQWO4=,tag:nvdd1HxgXrmqjSl92MmShw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBNndqYitp
            QkZmRWovc0dZTUxjTlhzOG5Kcy9tYS9XbVlubklnbWZrK0FLcApqTWdRTWtxRFRK
            M0tVYi9FTVdHYWJ3OWowL1Y5SDAzWWlMenc3WWZNKy80Ci0tLSBBOW1WYklUUkdT
            N0w0eU1xeXhTbjVZQWE3MlpNdzRuU1hEZUcrc25scmUwCngjKEoeYJz8RVrjhSno
            jf/yohpFSrCFHqT/PUrJDnrKKNyWu2hurctZeNhVlow13iyMfsDr/GCl1y1FAn44
            9G4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZXB1M2Y4cVZDdjEvcWxP
            YmF3S3pMdFBONFFSR0dXem5FQVJVOFJwU1VzCkdUdSswZnVjczliZms0am1BZWoz
            MWRPYkhjaHNZamo2TG9RbkwyN0VBY0kKLS0tIHhTZ3FiS2FqOUIyMUVqenRiblhx
            eGVZR3NKTERJUjI4d1pHTG4waERWVXcKpUmCKP2Y1E/yFld2YapnZFVEDoXTlw0L
            Pi2XO8B1sAF6I6gNe5kM9Ip1ma69937c0Ae9xlXx44CvchsHZk6WmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T08:16:31Z"
    mac: ENC[AES256_GCM,data:c6q4hZ5tw2hVogQiyBU5MQ5ZtyjShfw8NmUGf2YBRjq7wOHdgmKrt8LHm/KqdszLugBICflnw/xEnAcH9gWjPMIofensiKf2oh37icaVaWn3LvWi/D8F9y7KtA9XB/VfUIPCtBn6om9Jf7JOcYsN5uDNOEl1D9m2JLSDs5gA3NM=,iv:z/RmfvjMT/2eQEXv2DGdSp4zrqpPBc1lm8aHZ/DR3ws=,tag:aCStq/A6Roc8pH54jhyuHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
