apiVersion: v1
kind: Secret
metadata:
    labels:
        app: paperless
        managed-by: flux
    name: paperless-secrets
    namespace: paperless
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:m+BjV5yxLS6Ur8th9ZbvNFN9iuw=,iv:5GMdXctJ6lkiagBEXNbISTcpCOHfL3SuAXpynKmNSfs=,tag:CyLGozi680OVparqPr8kgw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:5whLVmDBhwpHz5pfPIgv2H0GJSP5DO8VpLpJvTgocQ4Vrz0Vmr3W4uWbUWhdC9Uq8pU=,iv:HQCFuRqEa9K0ZdxoZhAMddrGdwRXrEyYmcBNRPBXLvE=,tag:fLBLaP6eOE/qeG2JWIGhKw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:8jnmVeBmAmD4njpsIyXhkUgLotpNn2isOENnWBTj5O+YmkhCoyuf1tv3VhHOeDEJUfV1nmCuJ1bcaB/DHXLNEhnUtO3w6zx0w4VaRsMpyA/oWhY+MZSs07VBKmcezw1BCWiW+Ro37HBfhOwMPCclYcq92jk+N3PJqBABWIyWj1S9agMY3cEvKEiy1EVglEjVErphWf/7ltVfUDd4b5jAfRRIPtzn3P4zWzLXu9aDuaDoNCy70dxAoDkm40Ey/GOTUI0BZjbNzQ75Vfer8VY3H/tMFo+FOWNVybWwmCC4pUYKZsVrV2k3/X/EgEeBkqTlHjdQFwD4yaeeSRi84IpfcEn0ss4T//vZT2wQHnKiKKvf05WhW8iA13I0kbma89qsYmpuPW8AOxFZvP8c985cmxNdR7CNRjoaCjV7BO9Z3POzWJ8eIXQrst+zX9g=,iv:Ztkw7qmxPlNEC6zTKSeW7eJrEsqXcmu8ddNF26lApg8=,tag:+2RWZPmoJ1PPQs07Kv0l5Q==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:9uAymGwfvTqpnbxLuPYcDlcg4jSk43JnW8sJ,iv:BCkM6XiOi16oX1mJOWaXsRU5KHecpyKz4EtaU7/VXkw=,tag:6adtD4v17eW6iszuVT8kaw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+ExoJP+mz/mrSC1LgtipyVztmMc9Cmv5qUvf4vDdUfPm08d51GkK+Vy7532oQL/apww=,iv:s/3zhdPZxZjy9h3XQrA+JT3+xw/k8pgb5FvZ98ADU98=,tag:BpO4UjSC2J+UmnWx1C6x7Q==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBb2xTQVBG
            dSszcXA3QlBKcFhXOG1hekFvcXBYNWVGVjNPcmtDL2NtUW8xRgova3VzTEVnVFBJ
            Ny9ycGlrd1dXejI2WXBSTXljQlRxMjlacmc3WWxyRXgwCi0tLSBvSm1yWThvYVdX
            a282a0Q5bG5PWlR2Y3kzSzc1b1pkeWRSa1hFb1JuRXZVCgu4JEVAXyFmGKZoaqDN
            p1NidG0PpCGfsMOUG9h6FU6CSKYapYWvJ2LHi871WwQ6QlG/ibOhgGaXO+uvxV9H
            S1M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFNhaUdMa2VDVGVnOUg2
            b3ROWCt0WnQzMTJWNE9YQXF6WTFVeVpmUnpJCkplT3ZtZUVBc1c0clBmQ3dFbDcy
            dkZFVE92QUxZK0ZsZUcxaXM2K2dmVUkKLS0tIElmRUk1bnZLMVNjNDB0eUdoY25N
            VkNNR05SajR6aUZUbkNvRmthSU9YRmMK7mIzG0gzm8E0rq+ZpqDt5Xvd9Yq4q3AC
            h0JZ5ayLSGG6CuKrLEmn2yjd4CpS+fOBIxc29j8kpQPOrunzbM28SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T16:27:10Z"
    mac: ENC[AES256_GCM,data:jJLzCuvrKSIBE7/O08r6IT125VfFkoO6P0sEafaoOMOxd79IOt+MN+g2s5eXlOA2tl/46RQR8JfXI31d8IyZoSmKp1ofbT6phHBMTSzx40NFLcdUKY+/AxgY8RTcWA+004PeGTYwZCt0FrOoURKAvunlcRduypi7konVldwl2Ww=,iv:N9oKbbj1NmMOv9Ujkmj1l2YVczNPpTLHq07CMrtqq3M=,tag:sY/MoRf+bFCl0CHA8jhrng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
