apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
    labels:
        app: paperless
        managed-by: flux
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:hH5sOZ2/vjWfn6YSTWEnpVjsgh/hafXZnI35owVgnDLGSXp51qhVho76Ma5NXeEkgac=,iv:Nywk3FR7HteD4qTLPTiP6zTERLtB6a6HJDd1K1b0rb4=,tag:vNhk4rqrWl9V/qy7V4l8fg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nqLoCFiFQ2e1EkNw/ZxyCSUjUp8SjKa0CHO2GJRa0FgdcFoNlbJ7lnN6e/Ib13IlGdY=,iv:OvnRqCiLqHJ3zZDyAU803StzMajCGLBa/jWh7wmz2pY=,tag:z3It/Qcdn7bmhC4FH8IHlw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:UtA3QjvQXX49n/bJO0JEpQveG0iHkHtnWVJhcy8sZIobIobK15KZz3+M+adgGNLZ49I=,iv:Tl/etsoumhiY5OvW+C4Abo0x+mbWQM4o3XJF8H5t+do=,tag:3hL4yb9wn493cckE23qaoA==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:WPi0ADQzq2J6zMlxoCkaeUq4meI2ZRWqmKDU,iv:/3ixHYE2sQvwOpDXY6B8hyW76xUPrCKuv2xNwVq2UBc=,tag:sdA4BpgBlYQWykqF3nxaZA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:3GPv2zFg9+d9hbYLTgp9jZr5ALsMgPRjfCr6JlRW7BkhszvqnTNOMB0x/TnL/UrB81CLBYRXpl4IO3p2gsZ9TXKlWvW3xCEZ2EKvzqwqQj00A/6bt55qzi8bw2lnc834jJ3OEqKMi6/Kwd3d7HvNs+lu5x7nD2YzqRWh/45ZZ/2vKg0gSM+uSd1PbpimTVJZu5Vv+pPC01Olk5jn0dk4hDUeDjq5N++oKRJ7L4pTLCUD9T9BRsFpByW+LgOiPrmHfNIs3LYcoIF42GsASFAarZAUZM23+oJg05MbcXXYFUGXYpRZg/ovd0CzHGz9uqNnpRWR3vfvuncnaygdI2X8bzID6j867XpxE57x5VEwZ/F+XR+P+15HxLXUPdmIDeKtWQt/dTZZXFUK3tZMXk78+0wUZQUvGAF4t3x5y3EiXHg9TNAPXVVxURb8kjY=,iv:RVfjZZ7puX1BrhgQA6NUAwSEQNbVJPMlrITpO1q8FmE=,tag:CKnpCbglVaX5uZDOniGbmQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBNWZWbmw0
            RkFYRVU2ZE5lMlpiRzF2bjRTaHk0MDZ4NkxEOTNqNnhhMHB4ZgpJOURiM0ZPTU45
            R2xDRU5saFg3alB0bXhlSFZjYzBiR2dwMGlhNDhSVWg4Ci0tLSBDVkZuRENrMUFQ
            WlY4dnI3a1oyWjhMZ2RITVVVejRlSkJLb2RXMW1YaW5NCo5LMgcGjkn9m4aLUlp9
            xVyYcQoZKxii9yAFDn+DKTPpi0mJXMySo0OlCDKZdN62Hr1Jx5c/8Z2zLUvXOBr5
            p8E=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQTNwbDFEQVZBQ1FwSm0w
            a1h2OU9LTVNUV0pQcTBMS3dLZlBWMzVQUmtBCmlPcmlxR3RWZTFIWXJGTktpem42
            anUzRHJvcUhkdXdBUXBTTzhHQktnRncKLS0tIFlEc0ZjOERESXVNdGpseDAwcGhF
            TTFPZktJd3VscEFSV2NyZ2hGMlpJSEkKlZCTJIPUcXD+96cpTSzxFbGLrIaD0hYi
            oSPzxk0PBr8XHb2+k5zS/b5zkmTo1dvVRPSUhzq/ryOUGAErGeV7pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T17:21:28Z"
    mac: ENC[AES256_GCM,data:2m79cXP6fWYKxdzpr0sE4ohnWvMPlkeUgpvyXH5aFIJOkIhvMFf3MKyy+Aec+o40RmcUgHbzWmhpcHqq0WbMPkEBYcVuk0SwYFEZd36CqrKcltA8AnX4vqtc+62GpCWIbiEzHzBTfG6lVlRKV1CIQ0AuWBNLBsbJDrPohHuGeFM=,iv:7Q/j4EowC223uH6Z44kPvf9R+147YMd1Bfp3HKQE+FQ=,tag:W8rPogcGB7T+5K3MT6Ooaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
