apiVersion: v1
data:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:KOJGxORNXh41r1+wHJaZtkzWvKpSrdM6X5Je/WeegJOf9FCD1u0Anjk6yHGAi3gvnZ7Cu1VcOY7Kchh9gdcxriILiCx1qrg92Hhg7g==,iv:JDZVYPyCmUt4NgVQ7uKlsA9V26F2uU2qBWP2I2gUoeY=,tag:VYpU/hXmd6UIsiLV5iIZsA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:C3NsqoHCRF4nJ6HU/dvzwHqYIoIjFHd5mLte6108fqdBIeF6TLy9SA==,iv:wlE/PeAdfqu8gX4JXCs4ctFO9NqimGSzTLLEGCq7ys4=,tag:YFPwbpZE5itKPWlzNhwXkQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:36nciJ+agI45ps0SDcoZTCSWrMSZUeNBOG9rJN07I/WwxptSdPDQLw==,iv:hsxvujfufsm4G0FwazIX+he0NAljNwToV7DjoN8lxUU=,tag:v6t2J1WcilOyVLSLvrUKLw==,type:str]
    SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:XvEPhgT+61wiJ46SOafjqJrCTuIFuIoc,iv:3X+77vTDWwAqyjvm6c6Ff/s3myBQaI5yxokhTppa2b0=,tag:KU3Ld0gdUVkptfVdbahnkA==,type:str]
    SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:OTTwzqEtuXWDZWGeetsDKqS7WljszU+lW9Q5a8T6x+aV21aiWOwpBA==,iv:w2TQPEJGV0AtwHTB+YhGMtaBc1/NOU72frfN6BjWlMU=,tag:aUlsc02ZPZk/NlfxyP+I0w==,type:str]
    SEAFILE_SERVER_HOSTNAME: ENC[AES256_GCM,data:FLhztiOOVjpLPt6Nj17Fso0wlNA=,iv:CFVNgcBpYn7WaoTpWJzRS2iUOeZqY4SuY7VVIi443Mk=,tag:1TksYMNDKE2ifqvk+9IvFw==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-04-12T19:08:24Z"
    name: seafile-secrets
    namespace: seafile
    resourceVersion: "2096143"
    uid: 596c3470-72c9-4c51-afb6-61b2a93a3399
type: Opaque
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBdkJ0aVps
            YVdoOG9JbjNoemVlclJTTHorSDVHT2k0WXJFRkNKbnJsclVhYwpwSnlBU1VrQXV0
            eTVEVVpqWmw1Uk5raVFjK1BEZnYzZzJXK0ozRjVrOVZvCi0tLSBuNlpSSStXSXha
            VXlKTG1VTHhSQ2lMZWpXMnBmT2kwaDBmc1o3WUlkRytjCh0oDiS8XuumGdX90ilX
            WcKd9IK70z3tHglhTBaA/HnYyar811jx1GWZOb0s7Ji1OeBWxpEszLb5HTHqnuH0
            GzM=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGs2TE5udjVSZ1o4WWNn
            Q3IwUHp0ZlhMYzBPeFpuMkxFWHBraWh0RkRjCnZRRU9ac01JT2M3VjJiTUJhM2ll
            ZjdTRmpIemhnaURtTm5scXVoc2JucDgKLS0tIHRJT2NicWdQUVRKOWdlQVpYL21L
            cmpOa1p6Q08weEl6MFlEUDlGa2NBRHMKCgGCo/wXuByueIYlO3akAj5/0497Bje0
            bXclakQm56LxsicEubUx5b2CNpSVFD67l6yZ9iUa5+sqoTvzYVIQTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T19:08:46Z"
    mac: ENC[AES256_GCM,data:bmqUmvo12FGRNNrBUe5DA14uvL3+Goj39hsnoBQezQJIn0U8xbUqhpShPbge6Jh2tDbtIBkVk/HsiIhWxvmTxH2zsGWuCnHSPELLThCVtbeHZCROsFq2UtuRDAifcD9Cy4XvrnHzAYpKz9Va3q+VUczfoVLUq9BSgAOFEYtzlwI=,iv:xUeFCPPjl6PtMZ6MtInWXBCm0F6X6Roj2U8bgkeVwE4=,tag:6sFZV7l/2P5nsrJr5FjdMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
