apiVersion: v1
data:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:iHgwNO/BZjhRxQaZBHBeUJ6TATrjgYFi8+1ncqXVD+dM0kDmXEc6zw==,iv:JwhCuFpuLllBtxfzDvBG25/AaXJQXMzGKJjISFJgzP0=,tag:Vh1DxuAXAguUIq50zR+Ktw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:4ID5+CluJ25sAQcoRrYqLuEnjcTN5Rm+r81bpDpZ+axHUY0nA7IWqg==,iv:GT1y0pGCpFYbn9FhBcRM0GoKPQ0/D623j+Qmlzqftfw=,tag:yVIbEEVxzuW5eSfxTfmslw==,type:str]
    SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:3y9nUpg057E/5gI3JIc+OqdNil0Mtg2D,iv:94h0YL133Jt8Dxi+/z6xyslyZzo2vPxjcF9WQ0QrZYw=,tag:pdREQSlyERem1JxYD+yzbw==,type:str]
    SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:YQOQDOOloB38tLQbXoaRa7f87rsDUGexBFo8QemZzyMoKz9KRuWN3A==,iv:AGH4o3SgEtQpsXmZ1VWotuNUUJnKoyuCxWXOUWr+6m8=,tag:4ypq/3q8EpZZqQTUD7EHzQ==,type:str]
    SEAFILE_SERVER_HOSTNAME: ENC[AES256_GCM,data:hXRN8MGpFxDnqvl5SywQzMDD+Jk=,iv:rNQ7LFfREWy163NZct5rnDTXOpUEvSrhM0zAWbfKkbw=,tag:1E2Ao5YDZReKloDAyjNPUQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:TL4v1rHQkqmWJykoUIVoD0yieNMPDJ94+X3nJIgavI4SmrwjVloyLMjtpdEQ5y5v55iStsMlW60iP6kMtTUcX64GAmFUdm1UxoRg7/O/9ctUoO6dDAy36A==,iv:swiQLoc0IbaNjFx5OFRI1Rjq5x0nif08hKjwM0azFeM=,tag:10Wi7/vNBGWNhwgJGJdeUA==,type:str]
kind: Secret
metadata:
    name: seafile-secrets
    namespace: seafile
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBc0NNNHpX
            N1o2azVycXIrMFRRY3l3Z2VHZUtQTG1rVFRKTlREZzFwV1NtbwplRWplTlVXUzFP
            NzZYS0VJeDZoUUsxRFlDRzc2N0JIK01VVlpHQVFhZy9vCi0tLSBubWxzTmo5UWd0
            cXdIS2VaM25hd0QyalI0RWxUZW5EVmFMYmxXZlFnd3N3Cp3I5FoaqhSnjsSdMVHo
            1h9witPDOh+pTA7NKHi9lLIyQdb3B6xQrN9YOEkRH6S3GhXVMcdHf3sgGNcKZXQg
            hvI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3azhjOE1STCtvQ05LT0dK
            Njlpc08xQ21kYThhdVlKVjIvdVYvWmc1S1NJClJpcDJkOXJrQURWck9wTnRNOHlL
            R0FMTS94cVhpV2E3bUx5bHRMT1NoSXcKLS0tICtqelVjRE1Pa1FhaGE0SjVCOTU5
            WHAvbkw5UE9uSkhZN2hCb3drZFo2ZE0KK5BtMe8TWUfwl5K5AXEZzZ3dfTm4AqlK
            Uc5//Cg2VPuw20iD46t+kLsiIW/71DToiVK2+o8jZwB6XkorE7dLyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:45:47Z"
    mac: ENC[AES256_GCM,data:0aV14Bd23HuUcoM26w7VFNgPtFytxwwTVgzULffk2K6DUH0wCK/hRQDIz6Igcdv6Qmi5R/ufMUjh/lPoW0zTtzoh36NYTqzEOwr/Tlkjd12IjZ7IE+O7AjEWaJkbj/ZRgEDbbQqpNsnQI2WFZsAX7UbQBqXeSq5ermhIqapPNkI=,iv:0DWB55ZgkEOadWC1Z9GNJ1DCdQeGJlFXhVMaiVQ1ePg=,tag:1EQa+yB8ixrCTCwYamtj7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
