apiVersion: v1
data:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:Bd0coxnCp0LHNynk7PTD6vLxgp9/WXR6ogQ1XhIQ90aW0wyazd8ZC8YxnKCapVA8DrB87s7GBCRYVtrZOVqy0OERPRpo76vcxspirA==,iv:uW0taImuX1r9U5vgIV+rFwaL+aDj3VVDY1uk48g/DjU=,tag:J0z0RkFFJyToMY4zmdkwKA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:cxODkJqfBcrtyFAVbCuVUq2LsYNmtwRL6GIYN9C92O6Zinb0T4IIbg==,iv:v3aUcgDzN+0GSWOqboqqAedBrUy6vETu+aHENqQ6Vq4=,tag:AIZ2ylsbnFdCB5kF5oaV0Q==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:2p6DaZlBtJ95ljqWehJrdhEwMC5Po6C1Wgvo81LgiZzDee2fz+YuIA==,iv:p9U2zQJGvZUguJN4s6i6hfN9OTResEtpAA2ULimgICQ=,tag:tfCt5g3ugjq8B/TzAK2sbA==,type:str]
    SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:9UvWcA2kp/jhshrUZ94c8ME1ZKhUvIo9,iv:F+pzAqU1PuFefJZvtLeVbjhZMXUA3Qrlm7KT5UDR69I=,tag:wWrWkrZL0l+dHpn6cmIDCQ==,type:str]
    SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:gZX2jkFrpUG7t0PqSdCbD8KVNeL+0FofjmMwhLY3KNTffs2CjCtOrw==,iv:oeGox9ic9yI4fA/7/ebfdtvBNhm31j1kksUF2kBy4HY=,tag:6rWxhJIRNwL+9/0okcSyeg==,type:str]
    SEAFILE_SERVER_HOSTNAME: ENC[AES256_GCM,data:cUKLQWMXW294frcillVRKmIRM/E=,iv:2OKSgH8AAl8GsZUzUYfIHxnG3o7W3tERZbqv+I5+xmU=,tag:NtjcGHKp2+jhNPoQu3o1Qg==,type:str]
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: apps
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: seafile-secrets
    namespace: seafile
type: Opaque
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBMkpoWHVT
            dHdjWUdQdXoyeVJDTzRIaTdSdFd1SnhPS0JobmRTZkZESUdDSQpGZ055V29CYm9v
            UXdUYno5NXROcVhLajBURmp4K0lqZnE0Y1B0ckRzUnR3Ci0tLSBaVjhvNmVhUU9q
            ai9GYlRpaXZmTFdSRVZSeGRpT2lqeEZLMXk2ekpwaEo0CkfhrJ2Bolb+MuJ3zuGP
            OWQCuXT6AJ0kTshEzloeXVKRVXu2Us3ytyimjiGUsm71eawCGLTAdMkhvJZk1teK
            IGk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRkljMEFWdjU2ZlU4WTVH
            WDA3YzVTcnMrZEZ6UjJXMzAvb2JjWkFMRDJnClovWWFzQjdLQmQ5WUVjR3VOYTMw
            T3BKUGJBaWJWVmt5TG1odUZkVFZ4VVUKLS0tIFdvbkF5dmVYMDZ2K1lhZHAvSncy
            RGduMXlHcmlLQ0lHTlpySElsQWFlNjQKmRqUSCQ8ZmhaRjKFOS/CUPW3w7lT7aqK
            oSWygUVUPWkVXQEYu/pYk8Wk9Gcg832i2Az6OqZYhOH2JkMt2B2rHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T20:09:48Z"
    mac: ENC[AES256_GCM,data:MxlIUBJhx9quwTyGlFauzsin8N5BAHN3hY4DJGiy7LAcS9BZL/Je+zMWmFXbD0h48z44saB5A4f3EKrlsNMfVZr7tWd7dUG1sbz27CZyCK/+c/ryam1KvGJSHRVfkkK6ovQQ/FidNjM8fcc7b5VEC3i6RIFoR96CRn1H96MI0yo=,iv:UDem+UixOIrtl8XnQCvM/BoZot5owbtqG6ImUDA5diA=,tag:3pc9Xs+ByZWuBFPug8eTvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
