apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-enc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 5Gi
