---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgCKWquHN49mMIK6iZnNvxtNKpAQu9PsXxeqvM0xGzzUSoMgP13B/hxl7vw3/r8hviDFJflPTQAuuuKqFpJCasee4owOcmLLhfzkg9AMiAjafytdz+4GoUSUwHvQU6WmvFdgJvueMlIjPktdNLVA64I1BF77eobB5/BLSuvbWfOOICZa6EQF/Zz6AEiyEI0i5WFcxyC+Tz+h7Nj4s/OEhQz476SrlYLsLVJnK5vs/I1tjZlywWZEpSlDO41JAf6mK7IODE9qHH0ZS9Qi2T31ekpZxnYF1U8B9urfyLCkPFa4DDirSa04onxz4q5acRaud7lFuakXunSeaWuigRhzV51Wqhq/+up6A8myn0hePWGf43HPICt4d8oMGgz3TcJ80eKk203NNZSDLgfWup0lYThbSlzq8GXbTwf+XKzwevSjKX5t88uxNywnustXIDSdVN9xdyz99a/FvbKW875MbMLxO79epgUmtsG4zFA4i1jjli6+G3ALIISOoZOsknM3mMHNJrUqXXomTvxUdiUog4NUxAauXFnyuiK9hAvyujNwTvRvOxSLaS7SZqR9TQkhFWNLxrOGA0psGfxxoIWrkPadM1u/PLAOD+vb88tulzjB8M1Lb9w0A0abszaiRiYaNQacaBMnPF2GHFkpOfh5DrRzoYRSeNiWTMGvYow4bq5vCdnC9f8CeuSKPaIir2wxygUupPvMN25638JTzbrOsfyr8cn5MYdZpvnfE31qeyo=
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
