apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:ZBB8jfrkzqGHy88DZSPezCOsa2VlPyyiu/2l1b0c,iv:4N7WLMTbCuguTmqhw1iIguZQxhmA2BOKcPoTcRLAvUs=,tag:1ExRiFKfiXmQwsxXqEb+QA==,type:str]
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBbFB4WHRP
            cUptSk50TFJtNUFlZnpLNXBjN1VDVW1pb0xJcDJ4M0NpbThnRQpVZFBwL2FaVHJi
            ZDRzbWN1UXJwUTVFemRIcVcyTkZXMGtrWlpaUXo2dkxFCi0tLSArcncvYVdkdEt6
            a3pPbGxFaW5OcmI0Nk1JblJuZ0ZtOThtUGUxVFUxM0dzCrkP8j3VPABxzPI0rrJI
            LVnTcC4TxRNNwp2VzJH3IPnWkEW7l4N9odBKbu/sQ9UyV4P2wHhP2fxUJuyXcKiz
            hMg=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YTczRXFFaDBBSUc2V1J5
            R09BZlBvZ3pDV2h1a3BvZUozMkRWd2xmYW1FCjlzR0hZN2FmZ3hWVm8zRms2SjVC
            ZXlxeERpNmVvOTJQWWdQOU5KTlJtb1UKLS0tIDlaWHB3OVJJRnp3ZlFCK2VXajBD
            MjlUTTBtblZoUXpyUU9YNHI4Yng3Y2cKvCWHwNu5t71jqTseNYavnO7ttGU0IOe2
            iKmknR6WWoo25Pnk/HHRM+e1fKSGayOFjWP9XtiOqRvgIte5zwDjtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T17:31:45Z"
    mac: ENC[AES256_GCM,data:IMXzfPhnfjBYjSykL6Bm1jca7xbmbw3tnKmzVlmLpFm1HMHR9dE8Tg238mtk7E4BzjhwPpoWD1JJ2mMaSNgNzXYqCYuany0NrIrm9tPlBArU7oTN5cgz/BpYLiTdhbwPeX2mp/Xq7Z5L3EBQAvwY36Kbmtqzd0GgYzFabKEFYvo=,iv:WiaHKua2+LQk6QWlZkRUiRHCcaqKXDBUc2OE7K4vw6s=,tag:TdcSNSBhbA1F6UETZHgCEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
