apiVersion: v1
data:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:8tWufzmHJrqidBIH8ASTVAkhe6Wmufcg1/xwN6P5e4AXTX/Cz011cg==,iv:C1EzUf/I4sDVMX07QNNckmM1a6VMKQurqwU9q4Bk6Qw=,tag:Q9VZqy0mQuAoSBgFt0gojA==,type:str]
kind: Secret
metadata:
    name: pihole-secret
    namespace: pihole
sops:
    age:
        - recipient: age1yubikey1qvj2qyvcuk9a5h4mnw5g2kx29ar6r76jxf70z7p6ueywvs5x5pjy6veqz6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRlUFVMdyBBL1IxYnFG
            aTBWNERPR1ptS3RqbjBBcXA3SlBSdDlDWkdjUlBKVitiam5zSQpBN1ZPeko2Y3dO
            ODlTRCtIV3NoUFJGeWNQSXU2WEVrMXVYdkVvN2hmQ0ZzCi0tLSB3aUVYT2xvVCsy
            M2lIZDYrdWZUbWhpZlVFS3BaMm1ER2gvdjcwMXpaRUEwCj6UaenwvoWcGhh+w23k
            RtS63liS3hDqV4cAvGOix/m+6auQskkERDC+PAJDjxwItr1bRbwbuw4ytiaJHITB
            37I=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k7zs63jjpdchkw83achsfhpuhssk27s5rakwwkdnge5apgdsdy7q7fpy84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RTlEN2ZYbHNTNVlLRkNq
            ZmZ2NEVhU2FKd20ra051TGUrWGp5a20xeVc4Ck5yU2FreWI5VFVJMjlqUHg5NVBB
            d0pqMjg3VVJyL2hLMStLN2RNYmE0dlUKLS0tIFVmQml3WlJYZ1BXTktaeDgzMUZD
            L3dDTHU2OVREeEw3OFNTaXBuSkVnMUkKG+gOo6MD9dxDE9QEfzslm4KO/3aijuIs
            l0eGys+yURDMJdpnZ6XJBb8k1IYb4XxZDPqBY97JDkF2KgVCVfuqEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T21:21:52Z"
    mac: ENC[AES256_GCM,data:Xyc7Ti0KIvrERvfUxDYVv7CceuaHm60qfV+BTHeF8u9Bzptr4FF8OkFYgPqkA2falQnzH2mLU6hwQ3OFOy4Xj+Nmg1ZeMNeObQPDPZzEr74sITgBKfiKyAR/yj+FLrWO+0AKuirTWohHMTz6WooXBbf9FWl3rZk9hJQ3EmOaZLI=,iv:hl9QRmSSShR/5YieHMmjljgkXx/czmGiwjBxn+HCc64=,tag:8gJ6fvs8MgN6x7Xq9HEmlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
