---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgAF1viKuFgWlBrpPWFv9JxoAMFXiuBYRcf7BKAMWMO2tpaMyrZZnjIv2mxBUJu5Z1CScehCqCNEBfcVSE/YC9+pClB/ml3Dn0F0l9mJHDWOQrYMa1dGryaepMlxUcmXHI/raD714nmrnErhnNIqso6H8Kg6/VUCPxWTryBd75UO2jc4jxGycNmeKPzMJDa3z8nofoXDinlgc6IwmxeYYaXjLbGbBALxJ7RKRN4yt6eA915plaz6tZcFtcUI0Poh0/vOvHx0t0/p3NgSQ3jxHbvBZEtgKXdr9jz7iWGF8OFUszo5bypE3+wLUS5eQjiI/kXdvqoQlf9FrWCAh2Wz+BhmV74r16BY4g83zhPbgjMIC1EtVpCkF1tb16U1XGC8J07Cw11nJMTlBsp7RdWTkjWSz4IG70QXlozNvIxvV89NjaIa/P5qUwGm29ect1xLKgPkTe3/Ofwxuvm3bzRptobFgEC7knX1T/hzZntplyA1reybhLamSMvO4xyogPfe0XHxSSn3BoAIocgcluV1SGywbfWB9v1r9FMdXo5It1UvNcveyUPpmUN3HP453BhkywgD+LkEHEXi5mo8Mx1SDJ/cTVEo7SXFkr/JZlE4FtN1LVPvQH0EUpAqqI4c6jpaC4u6JR99nzitSMAKGoQfBne113aSBZ8tQzTw6UbQXoCzlKlX9Z+v1TJuTNRUj01dqCirGxy4KWXSCzbnpe5OOpIbS8SoSbpHHTs0E/XniZA=
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
